DROP TABLE IF EXISTS account;

CREATE TABLE account (
    id SERIAL PRIMARY KEY,
    username VARCHAR (200) NOT NULL UNIQUE,
    fname VARCHAR (200) NOT NULL,
    lname VARCHAR (200) NOT NULL,
    email VARCHAR (200) NOT NULL UNIQUE,
    password TEXT NOT NULL,
    created_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_date TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    last_login TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
)